AWSTemplateFormatVersion: '2010-09-09'
Description: MediaWiki Elasticache
Parameters:
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: RDS subnet IDs
  ElasticacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Elasticache security group ID
  NodeType:
    Type: String
    Description: Elasticache node type
    AllowedValues:
      - cache.t4g.micro
      - cache.t4g.small
      - cache.t4g.medium
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m6g.large
      - cache.m6g.xlarge
      - cache.m6g.2xlarge
      - cache.m6g.4xlarge
      - cache.m6g.8xlarge
      - cache.m6g.12xlarge
      - cache.m6g.16xlarge
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.r6g.large
      - cache.r6g.xlarge
      - cache.r6g.2xlarge
      - cache.r6g.4xlarge
      - cache.r6g.8xlarge
      - cache.r6g.12xlarge
      - cache.r6g.16xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
      - cache.r6gd.xlarge
      - cache.r6gd.2xlarge
      - cache.r6gd.4xlarge
      - cache.r6gd.8xlarge
      - cache.r6gd.12xlarge
      - cache.r6gd.16xlarge
    Default: cache.t4g.micro
Resources:
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: MediaWiki cache subnet group
      SubnetIds: !Ref Subnets
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SubnetGroup"
  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      AZMode: cross-az
      CacheNodeType: !Ref NodeType
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: memcached
      EngineVersion: 1.6.12
      NetworkType: dual_stack
      NumCacheNodes: 3
      Port: 11211
      PreferredAvailabilityZones: !GetAZs: ''
      PreferredMaintenanceWindow: 'sun:18:10-sun:20:10'
      VpcSecurityGroupIds:
        - !Ref ElasticacheSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-CacheCluster"
